parameters:
    cacheFolder: 'assoconnect/validator-bundle'

services:
    Pdp\Cache:
        class: Pdp\Cache
        arguments:
            - '%kernel.cache_dir%/%cacheFolder%'

    Pdp\CurlHttpClient:
        class: Pdp\CurlHttpClient

    Pdp\Manager:
        class: Pdp\Manager
        arguments:
            - '@Pdp\Cache'
            - '@Pdp\CurlHttpClient'

    AssoConnect\ValidatorBundle\Validator\Constraints\EmailValidator:
        arguments:
            $manager: '@Pdp\Manager'
        tags:
            - validator.constraint_validator

    AssoConnect\ValidatorBundle\Cache\CacheWarmer:
        arguments:
            - "%cacheFolder%"
        tags:
            - { name: kernel.cache_warmer, priority: 0 }