services:

    assoconnect_validator_bundle.email_validator:
        alias: AssoConnect\ValidatorBundle\Validator\Constraints\EmailValidator
        public: true

    AssoConnect\ValidatorBundle\Validator\Constraints\EmailValidator:
        arguments:
            $store: "@assoconnect_validator_bundle.tld_store"
        tags:
            - validator.constraint_validator

    assoconnect_validator_bundle.tld_store:
        alias: LayerShifter\TLDDatabase\Store

    LayerShifter\TLDDatabase\Store:
        class: LayerShifter\TLDDatabase\Store