services:
    Pdp\Cache:
        class: Pdp\Cache
        arguments:
            - '%kernel.cache_dir%/assoconnect/validator-bundle'

    Pdp\CurlHttpClient:
        class: Pdp\CurlHttpClient

    Pdp\Manager:
        class: Pdp\Manager
        arguments:
            - '@Pdp\Cache'
            - '@Pdp\CurlHttpClient'

    AssoConnect\ValidatorBundle\Validator\Constraints\EmailValidator:
        arguments:
            $manager: '@Pdp\Manager'
        tags:
            - validator.constraint_validator
