image: php:7.1

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq
  # Install php-intl
  - apt-get install libicu-dev -yqq
  - docker-php-ext-install intl
  # Install Xdebug
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  # Install composer
  - curl -sS https://getcomposer.org/installer | php
  # Install all project dependencies
  - php composer.phar install --dev


test:app:
  script:
  - php vendor/bin/phpunit --configuration phpunit.xml.dist --colors=never